site_name: UPPMAX Intro Day 1

repo_url: https://github.com/UPPMAX/uppmax_intro_day_1

nav:
  - Home: index.md
  - Overviews:
    - Schedule: overviews/schedule.md
    - UPPMAX Intro: overviews/uppmax_intro.md
    - UPPMAX Intro Day 1: overviews/uppmax_intro_day_1.md
  - Basic use with visual tools:
    - Introduction: sessions/introduction_visual.md
    - Login in general: sessions/login.md
    - Log in to the remote desktop environment: sessions/login_remote_desktop.md
    - Use the remote desktop environment: sessions/use_remote_desktop.md
    - File transfer using FileZilla: sessions/file_transfer_using_filezilla.md
  - Basic use from a terminal:
    - Introduction: sessions/introduction_terminal.md
    - Log in to the console environment: sessions/login_console.md
    - Use the terminal: sessions/use_terminal.md
    - File transfer using scp: sessions/file_transfer_using_scp.md
  - Doing real work:
    - Introduction: sessions/introduction_real_work.md
    - The module system: sessions/modules.md
    - Creating a bash script: sessions/scripts.md
    - The job scheduler: sessions/job_scheduler.md
    - Start an interactive session: sessions/start_interactive_session.md
  - Going deeper:
    - Introduction: sessions/introduction_going_deeper.md
    - Using an IDE: sessions/ide.md
    - Linux: sessions/linux.md
  - The bigger picture:
    - Clusters: sessions/clusters.md
    - NAISS: sessions/naiss.md
    - Apply for resources: sessions/getting_started.md
    - Bianca: sessions/bianca.md
    - HPC: sessions/hpcs.md
    - UPPMAX courses: sessions/courses.md
  - Misc:
    - About Richel: misc/richel.md
    - Evaluation: misc/evaluation.md
    - Exercise procedure: misc/exercise_procedure.md

theme:
  name: material
  greetings: Welcome to UPPMAX Intro Day 1
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/logo_color.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    
extra_css:
  - stylesheets/extra.css
      
markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg






