# Check that there is correct spelling in all files
name: Check spelling

# Check spelling on the 21st day of the month.
# 21st as the first letter of this repo is the 21st letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 21 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Remove files that I don't care about yet
        uses: |
            rm docs/sessions/bianca.md
            rm docs/sessions/command_line.md
            rm docs/sessions/getting_started.md
            rm docs/sessions/hpc.md
            rm docs/sessions/linux.md
            rm docs/sessions/naiss.md

      - uses: igsekor/pyspelling-any@v1.0.4



